name: Spigot-API
author: Niklas
version: 1.0.0
main: de.niklas.nikapi.spigot.NikAPI
commands:
  test:
    description: "Test"
    usage: "/test"
  paginated:
    description: "Test Paginated Menu"
    usage: "/paginated"
  lol:
    description: "test"
    usage: "/lol"
  add:
    description: "test"
    usage: "/add"
  config:
    description: "test"
    usage: "/config"
  spawn:
    description: "spawns a custom mob"
    usage: "/spawn"
  ymlconfig:
    description: "test config"
    usage: "/ymlconfig"
  customworld:
    description: "creates a custom world"
    usage: "/customworld"
  storagetest:
    description: "Storage Test"
    usage: "/storagetest"